stages:
  - build

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -f Dockerfile -t $LINK_REGISTRY_REPO/opsculun/web-to-container-webbaru:1.0.0 .
    - docker login -u $USER_REGISTRY -p $PASS_REGISTRY $LINK_REGISTRY
    - docker push $LINK_REGISTRY_REPO/opsculun/web-to-container-webbaru:1.0.0