apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-to-container
  namespace: cicd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: web-to-container
        image: registry.gitlab.com/opsculun/web-to-container/opsculun/web-to-container-webbaru:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: cicd
spec:
  selector:
    app: my-app
  ports:
    - name: app-svc
      port: 80
      targetPort: 3000
  type: ClusterIP
